spring.application.name=social-media
spring.datasource.url=jdbc:postgresql://ep-little-snow-a13y3z11-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_TwLAzHSRcW06&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=dzvjwaye0
cloudinary.api-key=549354688816346
cloudinary.api-secret=6j05eyqOCXWQlFGtRg5RyHzHIhk

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.application.security.jwt.secret-key=TranNhatNamHocVienCongNgheBuuChinhVienThong
spring.application.security.jwt.access-token=60000000
spring.application.security.jwt.refresh-token=360000000